version: '3,9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: listinha_user
      POSTGRES_DB: listinha_db

    ports:
      - "5432:5432"